samples: ["full_mock"]
#threads: 50
#centrifuge_db: "media/eternus1/data/metagenomes/users/igrab/imgdb3/IMG_VR3"
centrifuge_origin_db: "/media/eternus1/data/metagenomes/users/igrab/centrifuge_db/p+h+v"
kaiju_db: "/media/eternus1/nfs/projects/databases/kaijudb/kaiju_db_nr_euk.fmi"
kaiju_dmps: "/media/eternus1/nfs/projects/databases/kaijudb"
genomad_db: "/media/eternus1/data/metagenomes/users/igrab/genomad_db/genomad_db"
virsorter2_db: "/media/eternus1/data/metagenomes/users/igrab/vs2db/db"
