name: deepvirfinder_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6
  - numpy
  - theano=1.0.3
  - keras=2.2.4
  - scikit-learn
  - biopython
  - h5py=2.10.0
  - mkl-service=2.4.0
