name: virsorter2_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - virsorter=2.2.4
  - python >=3.6,<=3.10
  - ruamel.yaml =0.16
  - snakemake-minimal >=5.18,<=5.26
  - click >=7
  - git
  - cookiecutter
  - mamba=1
  - conda-package-handling <=1.9
